"""Deterministic Playwright execution with AI fallback.

Read this after `step_generator.py`, `failure_injector.py`, and
`ai_recovery.py`. This is the Phase 2 orchestrator below the FastAPI route:
it executes generated steps, injects one controlled selector failure, calls the
AI recovery agent, then returns the decision trace rows the UI already knows how
to render.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import time
from collections.abc import Awaitable, Callable

from playwright.async_api import Page, TimeoutError as PlaywrightTimeoutError
from playwright.async_api import async_playwright

from backend.ai_recovery import AIRecoveryError, extract_interactive_dom, recover_step
from backend.decision_trace import trace_row
from backend.failure_injector import apply_failure_injection
from backend.models import ExecutionMode, StepResult, TestStep


StepExecutor = Callable[[Page, TestStep], Awaitable[None]]


class PlaywrightRunError(RuntimeError):
    """Raised for execution failures that cannot be recovered."""


async def _execute_step(page: Page, step: TestStep) -> None:
    """Execute the small action vocabulary generated by `step_generator.py`."""

    action = step.action.lower()

    if action == "navigate":
        if not step.url:
            raise PlaywrightRunError("navigate step requires a url")
        await page.goto(step.url, wait_until="domcontentloaded", timeout=30_000)
        return

    if not step.selector:
        raise PlaywrightRunError(f"{action} step requires a selector")

    locator = page.locator(step.selector).first

    if action == "fill":
        await locator.fill(step.value or "", timeout=10_000)
        return

    if action == "click":
        await locator.click(timeout=10_000)
        return

    if action.startswith("assert"):
        # For the MVP, assertions mean "the target exists and is visible".
        # Phase 4 can make this richer once the core recovery loop is working.
        await locator.wait_for(state="visible", timeout=10_000)
        return

    raise PlaywrightRunError(f"Unsupported action: {step.action}")


def _elapsed_ms(start: float) -> int:
    return max(1, round((time.perf_counter() - start) * 1000))


def _short_error(exc: Exception) -> str:
    text = str(exc).strip()
    return text[:700] if text else exc.__class__.__name__


async def _run_single_step(
    *,
    page: Page,
    original_step: TestStep,
    execution_mode: ExecutionMode,
    promoted_step: TestStep | None = None,
) -> StepResult:
    start = time.perf_counter()
    runtime_step = promoted_step or original_step
    injected_failure = None

    # Approved promotions are the learning loop: if a human already accepted a
    # recovered selector, run it deterministically and do not inject drift again.
    using_promoted_step = promoted_step is not None

    # Only the hybrid fallback mode demonstrates the assignment's fake UI drift,
    # and only when no promoted deterministic step exists yet.
    if execution_mode == "deterministic_with_fallback" and not using_promoted_step:
        runtime_step, injected_failure = apply_failure_injection(original_step)

    try:
        await _execute_step(page, runtime_step)
        return trace_row(
            step=original_step,
            status="passed",
            mode_used="agentic" if execution_mode == "agentic" else "deterministic",
            duration_ms=_elapsed_ms(start),
            customer_explanation=(
                "Used the human-approved promoted selector deterministically."
                if using_promoted_step
                else "The step ran successfully without AI recovery."
            ),
        )
    except (PlaywrightTimeoutError, PlaywrightRunError, Exception) as exc:
        error = _short_error(exc)

        if execution_mode == "deterministic":
            return trace_row(
                step=original_step,
                status="failed",
                mode_used="deterministic",
                error=error,
                duration_ms=_elapsed_ms(start),
            )

        try:
            dom_snapshot = await extract_interactive_dom(page)
            recovered_step, suggestion = await recover_step(
                original_step=original_step,
                failed_step=runtime_step,
                error=error,
                dom_snapshot=dom_snapshot,
            )
            await _execute_step(page, recovered_step)
            injected_context = (
                f" Injected failure reason: {injected_failure.reason}"
                if injected_failure
                else ""
            )
            return trace_row(
                step=original_step,
                status="recovered",
                mode_used="ai_recovery",
                error=error,
                agent_action=(
                    f"Recovered with {suggestion.recovered_action} on "
                    f"{suggestion.recovered_selector}"
                ),
                agent_reasoning=suggestion.technical_reasoning + injected_context,
                customer_explanation=suggestion.customer_explanation,
                duration_ms=_elapsed_ms(start),
                failed_step=runtime_step,
                recovered_step=recovered_step,
            )
        except (AIRecoveryError, PlaywrightTimeoutError, PlaywrightRunError, Exception) as recovery_exc:
            return trace_row(
                step=original_step,
                status="failed",
                mode_used="ai_recovery",
                error=f"{error} | Recovery failed: {_short_error(recovery_exc)}",
                duration_ms=_elapsed_ms(start),
            )


async def run_steps(
    steps: list[TestStep],
    *,
    execution_mode: ExecutionMode,
    promoted_steps: dict[str, TestStep] | None = None,
) -> list[StepResult]:
    """Run generated steps and return decision-trace rows."""

    headless = os.getenv("PLAYWRIGHT_HEADLESS", "true").lower() != "false"
    results: list[StepResult] = []
    promoted_steps = promoted_steps or {}

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=headless)
        page = await browser.new_page()

        try:
            for step in steps:
                result = await _run_single_step(
                    page=page,
                    original_step=step,
                    execution_mode=execution_mode,
                    promoted_step=promoted_steps.get(step.step_id),
                )
                results.append(result)

                # Stop after an unrecovered failure. Continuing would make later
                # errors misleading because the browser is in an unknown state.
                if result.status == "failed":
                    break
        finally:
            await browser.close()

    return results


async def _cli() -> None:
    parser = argparse.ArgumentParser(description="Run hardcoded steps with Playwright.")
    parser.add_argument(
        "--mode",
        default="deterministic_with_fallback",
        choices=["deterministic", "deterministic_with_fallback", "agentic"],
    )
    args = parser.parse_args()
    steps = [
        TestStep(
            step_id="step_1",
            description="Navigate to products page",
            action="navigate",
            url="https://automationexercise.com/products",
            expected_outcome="Products page loads",
        ),
        TestStep(
            step_id="step_2",
            description="Fill the product search field",
            action="fill",
            selector="#search_product",
            value="tshirt",
            expected_outcome="Search term is entered",
        ),
        TestStep(
            step_id="step_3",
            description="Submit the product search",
            action="click",
            selector="#submit_search",
            expected_outcome="Search results are shown",
        ),
    ]
    results = await run_steps(steps, execution_mode=args.mode)
    print(json.dumps([result.model_dump() for result in results], indent=2))


if __name__ == "__main__":
    asyncio.run(_cli())
